DROP DATABASE IF EXISTS drgtrdcntr;
CREATE DATABASE IF NOT EXISTS drgtrdcntr;

DROP DATABASE IF EXISTS bhaavbhumi;
CREATE DATABASE IF NOT EXISTS bhaavbhumi;

DROP DATABASE IF EXISTS citycenter;
CREATE DATABASE IF NOT EXISTS citycenter;

DROP DATABASE IF EXISTS mnglmcity;
CREATE DATABASE IF NOT EXISTS mnglmcity;

DROP DATABASE IF EXISTS mhvrtrdcntr;
CREATE DATABASE IF NOT EXISTS mhvrtrdcntr;

DROP DATABASE IF EXISTS iseries;
CREATE DATABASE IF NOT EXISTS iseries;

DROP DATABASE IF EXISTS smartcity;
CREATE DATABASE IF NOT EXISTS smartcity;

DROP DATABASE IF EXISTS masterschema;
CREATE DATABASE IF NOT EXISTS masterschema;

