DROP DATABASE IF EXISTS `bhaavbhumi`;
DROP DATABASE IF EXISTS `bhaavbhumiv2`;
DROP DATABASE IF EXISTS `businesspark`;
DROP DATABASE IF EXISTS `businessparkv2`;
DROP DATABASE IF EXISTS `citycenterv2`;
DROP DATABASE IF EXISTS `dhabbav2`;
DROP DATABASE IF EXISTS `drgtrdcntr`;
DROP DATABASE IF EXISTS `drgtrdcntrv2`;
DROP DATABASE IF EXISTS `galaxyheights`;
DROP DATABASE IF EXISTS `kalpavrish`;
DROP DATABASE IF EXISTS `kalpavrishv2`;
DROP DATABASE IF EXISTS `masterschema`;
DROP DATABASE IF EXISTS `mgrental`;
DROP DATABASE IF EXISTS `mhvrtrdcntrv2`;
DROP DATABASE IF EXISTS `riddhisiddhi`;
DROP DATABASE IF EXISTS `riddhisiddhiv2`;
DROP DATABASE IF EXISTS `schoolv2`;
DROP DATABASE IF EXISTS `smartcity`;
DROP DATABASE IF EXISTS `smartcityv2`;
DROP DATABASE IF EXISTS `suncitynx`;
DROP DATABASE IF EXISTS `suncitynxv2`;
CREATE DATABASE `suncitynx`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `kalpavrish`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `riddhisiddhi`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `smartcity`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `businesspark`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `drgtrdcntr`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `citycenter`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `school`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `bhaavbhumi`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `dhabba`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `mhvrtrdcntr`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE `masterschema`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

